package cli

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

const driverTemplate = `// Code generated by fox-openapi. DO NOT EDIT.
package main

import (
	{{- if eq .Format "json" }}
	"encoding/json"
	{{- end }}
	"fmt"
	"os"

	"github.com/fox-gonic/fox"
	openapi "github.com/fox-gonic/fox-openapi"
	{{- if .UsesOpenAPI3 }}
	"github.com/getkin/kin-openapi/openapi3"
	{{- end }}
	{{- if eq .Format "yaml" }}
	"github.com/goccy/go-yaml"
	{{- end }}

	userentry {{quote .Entry.ImportPath}}
	{{- if .HasHook }}
	userhook {{quote .Hook.ImportPath}}
	{{- end }}
)

func main() {
	fox.SetMode(fox.ReleaseMode)
	fox.DefaultWriter = os.Stderr
	engine{{if .Entry.ReturnsError}}, err{{end}} := userentry.{{.Entry.FuncName}}()
	{{- if .Entry.ReturnsError }}
	if err != nil {
		fmt.Fprintf(os.Stderr, "entry returned error: %v\n", err)
		os.Exit(1)
	}
	{{- end }}
	opts := []openapi.Option{
		{{- range .OptionSnippets }}
		{{.}},
		{{- end }}
	}
	{{- if .HasHook }}
	opts = append(opts, userhook.{{.Hook.FuncName}}()...)
	{{- end }}
	g := openapi.New(engine, opts...)
	spec := g.Spec()
	{{- if .InfoDescription }}
	spec.Info.Description = {{quote .InfoDescription}}
	{{- end }}
	{{- range .ServerDescriptions }}
	if len(spec.Servers) > {{.Index}} {
		spec.Servers[{{.Index}}].Description = {{quote .Description}}
	}
	{{- end }}
	{{- if .TagSnippets }}
	spec.Tags = openapi3.Tags{
		{{- range .TagSnippets }}
		{{.}},
		{{- end }}
	}
	{{- end }}
	var out []byte
	var err2 error
	{{- if eq .Format "json" }}
	out, err2 = json.MarshalIndent(spec, "", "  ")
	{{- else }}
	out, err2 = yaml.Marshal(spec)
	{{- end }}
	if err2 != nil {
		fmt.Fprintf(os.Stderr, "generate spec: %v\n", err2)
		os.Exit(1)
	}
	for _, w := range g.Warnings() {
		fmt.Fprintln(os.Stderr, "WARN:", w)
	}
	if _, err := os.Stdout.Write(out); err != nil {
		fmt.Fprintf(os.Stderr, "write stdout: %v\n", err)
		os.Exit(1)
	}
}
`

type DriverData struct {
	Entry              Entry
	Hook               Hook
	HasHook            bool
	Format             string
	OptionSnippets     []string
	InfoDescription    string
	ServerDescriptions []ServerDescription
	TagSnippets        []string
	UsesOpenAPI3       bool
}

type ServerDescription struct {
	Index       int
	Description string
}

func DriverDir(cfg Config) string {
	return filepath.Join(cfg.Workdir, ".fox-openapi", "driver")
}

func WriteDriver(cfg Config, entry Entry, hook *Hook) (string, error) {
	driverDir := DriverDir(cfg)
	if err := os.MkdirAll(driverDir, 0o755); err != nil {
		return "", fmt.Errorf("create driver dir: %w", err)
	}
	data, err := BuildDriverData(cfg, entry, hook)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	tmpl := template.Must(template.New("driver").Funcs(template.FuncMap{"quote": strconv.Quote}).Parse(driverTemplate))
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render driver: %w", err)
	}
	if err := os.WriteFile(filepath.Join(driverDir, "main.go"), buf.Bytes(), 0o644); err != nil {
		return "", fmt.Errorf("write driver: %w", err)
	}
	return driverDir, nil
}

func BuildDriverData(cfg Config, entry Entry, hook *Hook) (DriverData, error) {
	sources, err := absoluteSources(cfg.Workdir, cfg.Sources)
	if err != nil {
		return DriverData{}, err
	}
	snippets := []string{
		fmt.Sprintf("openapi.Info(%s, %s)", quoteDefault(cfg.Info.Title, "Fox API"), quoteDefault(cfg.Info.Version, "0.0.0")),
	}
	for _, server := range cfg.Servers {
		if server.URL != "" {
			snippets = append(snippets, fmt.Sprintf("openapi.Server(%s)", strconv.Quote(server.URL)))
		}
	}
	if len(sources) > 0 {
		quoted := make([]string, 0, len(sources))
		for _, source := range sources {
			quoted = append(quoted, strconv.Quote(source))
		}
		include := ""
		if cfg.IncludeTestFiles {
			include = ", openapi.IncludeTestFiles()"
		}
		snippets = append(snippets, fmt.Sprintf("openapi.Source([]string{%s}%s)", strings.Join(quoted, ", "), include))
	}
	for _, name := range sortedSchemeNames(cfg.SecuritySchemes) {
		snippets = append(snippets, fmt.Sprintf("openapi.SecurityScheme(%s, %s)", strconv.Quote(name), securitySchemeSnippet(cfg.SecuritySchemes[name])))
	}
	serverDescriptions := make([]ServerDescription, 0, len(cfg.Servers))
	for i, server := range cfg.Servers {
		if server.Description != "" {
			serverDescriptions = append(serverDescriptions, ServerDescription{Index: i, Description: server.Description})
		}
	}
	tagSnippets := make([]string, 0, len(cfg.Tags))
	for _, tag := range cfg.Tags {
		if tag.Name != "" {
			tagSnippets = append(tagSnippets, tagSnippet(tag))
		}
	}
	data := DriverData{
		Entry:              entry,
		Format:             cfg.Format,
		OptionSnippets:     snippets,
		InfoDescription:    cfg.Info.Description,
		ServerDescriptions: serverDescriptions,
		TagSnippets:        tagSnippets,
		UsesOpenAPI3:       len(tagSnippets) > 0 || len(cfg.SecuritySchemes) > 0,
	}
	if hook != nil {
		data.Hook = *hook
		data.HasHook = true
	}
	return data, nil
}

func absoluteSources(workdir string, sources []string) ([]string, error) {
	result := make([]string, 0, len(sources))
	for _, source := range sources {
		if source == "" {
			continue
		}
		path := source
		suffix := ""
		if strings.HasSuffix(path, "/...") {
			path = strings.TrimSuffix(path, "/...")
			suffix = "/..."
		}
		if !filepath.IsAbs(path) {
			path = filepath.Join(workdir, path)
		}
		abs, err := filepath.Abs(path)
		if err != nil {
			return nil, fmt.Errorf("resolve source %s: %w", source, err)
		}
		result = append(result, filepath.ToSlash(abs)+suffix)
	}
	return result, nil
}

func quoteDefault(value, fallback string) string {
	if value == "" {
		value = fallback
	}
	return strconv.Quote(value)
}

func sortedSchemeNames(schemes map[string]Scheme) []string {
	names := make([]string, 0, len(schemes))
	for name := range schemes {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func securitySchemeSnippet(s Scheme) string {
	parts := []string{}
	add := func(field, value string) {
		if value != "" {
			parts = append(parts, fmt.Sprintf("%s: %s", field, strconv.Quote(value)))
		}
	}
	add("Type", s.Type)
	add("Description", s.Description)
	add("Name", s.Name)
	add("In", s.In)
	add("Scheme", s.Scheme)
	add("BearerFormat", s.BearerFormat)
	add("OpenIdConnectUrl", s.OpenIDConnectURL)
	if s.Flows != nil {
		parts = append(parts, "Flows: "+oauthFlowsSnippet(s.Flows))
	}
	return "&openapi3.SecurityScheme{" + strings.Join(parts, ", ") + "}"
}

func oauthFlowsSnippet(flows *OAuthFlows) string {
	parts := []string{}
	if flows.Implicit != nil {
		parts = append(parts, "Implicit: "+oauthFlowSnippet(flows.Implicit))
	}
	if flows.Password != nil {
		parts = append(parts, "Password: "+oauthFlowSnippet(flows.Password))
	}
	if flows.ClientCredentials != nil {
		parts = append(parts, "ClientCredentials: "+oauthFlowSnippet(flows.ClientCredentials))
	}
	if flows.AuthorizationCode != nil {
		parts = append(parts, "AuthorizationCode: "+oauthFlowSnippet(flows.AuthorizationCode))
	}
	return "&openapi3.OAuthFlows{" + strings.Join(parts, ", ") + "}"
}

func oauthFlowSnippet(flow *OAuthFlow) string {
	parts := []string{}
	if flow.AuthorizationURL != "" {
		parts = append(parts, "AuthorizationURL: "+strconv.Quote(flow.AuthorizationURL))
	}
	if flow.TokenURL != "" {
		parts = append(parts, "TokenURL: "+strconv.Quote(flow.TokenURL))
	}
	if flow.RefreshURL != "" {
		parts = append(parts, "RefreshURL: "+strconv.Quote(flow.RefreshURL))
	}
	if len(flow.Scopes) > 0 {
		keys := make([]string, 0, len(flow.Scopes))
		for key := range flow.Scopes {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		scopeParts := make([]string, 0, len(keys))
		for _, key := range keys {
			scopeParts = append(scopeParts, strconv.Quote(key)+": "+strconv.Quote(flow.Scopes[key]))
		}
		parts = append(parts, "Scopes: openapi3.StringMap[string]{"+strings.Join(scopeParts, ", ")+"}")
	}
	return "&openapi3.OAuthFlow{" + strings.Join(parts, ", ") + "}"
}

func tagSnippet(tag TagConfig) string {
	parts := []string{"Name: " + strconv.Quote(tag.Name)}
	if tag.Description != "" {
		parts = append(parts, "Description: "+strconv.Quote(tag.Description))
	}
	if tag.ExternalDocs != nil {
		docs := []string{}
		if tag.ExternalDocs.URL != "" {
			docs = append(docs, "URL: "+strconv.Quote(tag.ExternalDocs.URL))
		}
		if tag.ExternalDocs.Description != "" {
			docs = append(docs, "Description: "+strconv.Quote(tag.ExternalDocs.Description))
		}
		parts = append(parts, "ExternalDocs: &openapi3.ExternalDocs{"+strings.Join(docs, ", ")+"}")
	}
	return "&openapi3.Tag{" + strings.Join(parts, ", ") + "}"
}

func CleanupDriver(driverDir string, keep bool) {
	if !keep {
		_ = os.RemoveAll(driverDir)
		_ = os.Remove(filepath.Dir(driverDir))
	}
}
